[package]
name = "UpdateWindowsApplications"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
dirs = "5.0.1"
owo-colors = "4.1.0"
serde = { version = "1.0.214", features = ["derive"] }
toml = "0.8.19"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1.12"